listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;
srs_log_level       info;

http_api {
    enabled         on;
    listen          1985;
    crossdomain     on;
    auth {
        enabled         on;
        # Override via env SRS_HTTP_API_AUTH_USERNAME
        username        admin;
        # Override via env SRS_HTTP_API_AUTH_PASSWORD
        password        admin;
    }
}

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
    crossdomain     on;
}

vhost live-push.example.com {
    publish {
        firstpkt_timeout  20000;
        normal_timeout    7000;
    }
    http_hooks {
        enabled         on;
        on_publish      http://web:3000/api/srs/publish;
        on_unpublish    http://web:3000/api/srs/unpublish;
    }
}

vhost live.example.com {
    play {
        gop_cache           off;
        queue_length        10;
        time_jitter         full;
    }
    http_remux {
        enabled             on;
        mount               [vhost]/[app]/[stream].flv;
        hstrs               on;
        fast_cache          30;
    }
    hls {
        enabled         on;
        hls_fragment    10;
        hls_window      60;
        hls_path        ./objs/nginx/html;
    }
    http_hooks {
        enabled         on;
        on_play         http://web:3000/api/srs/play;
        on_stop         http://web:3000/api/srs/stop;
    }
}
